version: "3"

services:
  datastore_emulator:
    image: quay.io/gumo/datastore-emulator
    environment:
      DATASTORE_PROJECT_ID: test-project
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - "8081:8081"
    volumes:
      - datastore-emulator-storage:/opt/data
      - .:/app:cached
    # command: start-datastore --no-store-on-disk --consistency=1.0

  datastore_viewer:
    image: quay.io/gumo/datastore-viewer:develop
    environment:
      DATASTORE_VIEWER_HOST: 0.0.0.0
      DATASTORE_VIEWER_PORT: 18081
      GOOGLE_CLOUD_PROJECT: test-project
      DATASTORE_EMULATOR_HOST: datastore_emulator:8081
      PYTHONPATH: /app
      DEBUG: "true"
    depends_on:
      - datastore_emulator
    ports:
      - "18081:18081"
    volumes:
      - .:/app:cached
    command: |
      bash -ex -c "
      pip install -r requirements.txt
      ./bin/datastore-viewer
      "

  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - webapp-yarn-cache:/usr/local/share/.cache/yarn
    working_dir: /app/webapp
    ports:
      - "3000:3000"
    depends_on:
      - datastore_viewer
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      # PROXY_URL: http://datastore_viewer:18081  # TODO: Configure in webapp/package.json
    command: |
      bash -ex -c "
      sleep 1
      ls node_modules/
      yarn install
      yarn run start
      "

volumes:
  datastore-emulator-storage:
    driver: local
  webapp-yarn-cache:
    driver: local
